import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {PokemonProvider} from "@/context/pokemon";
import SessionWrapper from "@/lib/auth/SessionWrapper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <PokemonProvider>
            <div className="flex min-h-screen flex-col">
              <Navbar />
              <main className="flex flex-grow justify-center">{children}</main>
            </div>
          </PokemonProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
